sudo: required
dist: xenial
language: php
branches:
  only:
    - master
php:
  -  7.4
    
before_script: 
  - composer require atoum/atoum

script: 
  - vendor/bin/atoum
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
